### ISSUE TITLE
Repository about typo

### ISSUE THREAD

**Issue by CatsAreFluffy** [metamath/lamp-guide#136]
The about section for this repository references "the matamath-lamp proof assistant". As far as I know there is no proof assistant called "matamath-lamp", so presumably this is a typo.

**Comment by expln** [comment]
I spent some time to understand why matamath-lamp doesn't exist. But then I noticed the typo m**A**tamath-lamp :) I don't have possibility to modify the About section of this repo. Waiting for David to fix this.

**Comment by david-a-wheeler** [comment]
@expln - thanks for explaining it, I didn't see the "a"! Fixed.
