### ISSUE TITLE
Create introduction videos with audio

### ISSUE THREAD

**Issue by david-a-wheeler** [metamath/lamp-guide#32]
I plan to create introduction videos with audio, just like I did with mmj2. I basically intend to walk through the tutorial portion of lamp-guide.

I don't plan to do this until metamath-lamp has made some more changes. Things will probably continue to change, but I don't want viewers to see anything *too* different. In particular I want to wait for:

* The addition of "Explorer"
* Using a "G" type (Goal) - making the goal explicit, early on, will make it easier to see "what is the goal". Igor's still thinking about whether or not to do this.
* Improving smartphone support. In particular, I'm hoping "long press" will be supported, because then it's easy to explain ("press down long time to do alt-left click"), and the UI is essentially the same for all. Reducing the space used at the top (e.g., by overflowing entries to a "..." entry) would be valuable too.

**Comment by expln** [comment]
I think a video tutorial will be very valuable. I will prioritize the features you've mentioned. In particular:

> The addition of "Explorer"

That's almost done. 

> Using a "G" type (Goal) - making the goal explicit, early on, will make it easier to see "what is the goal". Igor's still thinking about whether or not to do this.

I decided to implement this. Just need some time :)

> I'm hoping "long press" will be supported

That's also almost done, should be ready soon.

> Reducing the space used at the top (e.g., by overflowing entries to a "..." entry) would be valuable too.

I will reply regarding that later. I need to do some analysis and experiment.

**Comment by david-a-wheeler** [comment]
Awesome! I await with eager anticipation!!

**Comment by david-a-wheeler** [comment]
My current thinking is that I'll create a video focusing on 2+2=4, using the lamp-guide material.

I don't know how much changing the unification algorithm will affect things; I suspect it'd have a powerful impact.

**Comment by expln** [comment]
@david-a-wheeler 

Hi David,

Looks like all the required for the video tutorial features are ready on dev.

I have not documented many of the new features I've recently added.
But I think this should not be a problem for you now, because you already know almost everything (if not everything) in mm-lamp interface.

Next, I will go through all the open issues and check if there is anything very simple to implement (like changing labels, adding trivial onEnter and onEscape handlers, etc.).
After that I will document all the recent changes in corresponding issues and release v11 (if no critical bugs are found).

If you plan to explain in the video how syntax in set.mm "works", a few technics I am demonstrating in the below video may be useful.
Those technics are not obvious from the mm-lamp interface, but I will not be surprised if you have already noticed them.

https://drive.google.com/file/d/13ihXqjKTab1RAJsr-V70_Pl4oFukdKAl/view?usp=sharing

**Comment by david-a-wheeler** [comment]
Sounds great!

I plan to update the guide for version 11, then create video(s). My plan is to focus on 2+2=4 to start with, hinting at broader functionality without trying to show absolutely everything in the first video.

**Comment by david-a-wheeler** [comment]
Here's my part 1, which is just a quick intro & tries to help people who
"stumble" into the video & may not know what a Metamath is:
https://youtu.be/b-RfoUuQpAQ

Let me know of any serious problems with this part. That video is "unpublished" in the sense that the link isn't public, so I can re-record it if there's a serious problem.

Actual content to follow, probably as a "part 2" instead of trying to merge them. I intend to show 2+2=4 as my (first) demo, in case you weren't sure if that was true :-). I'll use an updated lamp-guide as my script.

**Comment by expln** [comment]
Great introduction video! I like it!

One thing I noticed at the end - mouse movements as if you were clicking buttons to stop recording. This is not a problem. Not sure if you've done this intentionally or not. But I guess you are not editing the video before publication. Just in case you need, I can help with video editing, like cutting out some long-running processes, for example, when you use bottom-up prover. Just let me know. (I am not a master in video editing, but I can do some simple things like cutting out parts of a video).

> I intend to show 2+2=4 as my (first) demo, in case you weren't sure if that was true.

The only reason why I thought the demo may not be recorded is the case when something unexpected is found in mm-lamp which would make it unusable :)

I am planning to release v11 tomorrow. For the next versions I hope releases will be more frequent and will contain fewer changes each.

**Comment by david-a-wheeler** [comment]
Editing help would be great! I think the only issue in part 1 is the extra length at the end.

Here's the draft of part 2:
https://youtu.be/b-RfoUuQpAQ

**Comment by expln** [comment]
The part 2 is also great!

If you send me the original file with the part 1 I can remove the extra length. But I don't think the extra length is a real issue though :)

**Comment by david-a-wheeler** [comment]
I've posted part 1 here:

https://drive.google.com/file/d/1J5gXbrQ8Qbsc-rv3CKUxihe0hFP8ZbGR/view?usp=sharing

If you could remove the extra length at the end that'd be great!

I'll need to eventually remove it from Google drive, it takes a lot of space. :-).

**Comment by expln** [comment]
Here is the trimmed part 1 video. If I trimmed it too much I can change it (then please let me know at what time the video should end).

https://drive.google.com/file/d/1638hL6S7Cmr0eISPQ87nkUz9GLhMwwr1/view?usp=sharing

The original video file size is 10MB. The trimmed one is 33MB.

Some key parameters of the original file are:
Frame width: 1920
Frame height: 1080
Total bit rate: 313kbps
Frame rate: 25 frames/second

Same key parameters of the updated file are:
Frame width: 1920
Frame height: 1080
Total bit rate: 1100kbps
Frame rate: 25 frames/second

I think the difference in `Total bit rate` makes this difference in size. But I didn't find how to set `Total bit rate` less than 1100kbps (I am using CapCut video editor).

You may remove the original video file from Google Drive (I saved it on my computer).

**Comment by david-a-wheeler** [comment]
Can you splice *in* a replacement in a video?

Theere's a part of part 2 I'd like to redo.

**Comment by expln** [comment]
Yes, I can splice in too.

**Comment by david-a-wheeler** [comment]
I just realized that I *have* some video editing software.

Tell you what, let me do the video edits, & hopefully that will give you more time to create cool improvements to metamath-lamp :-).

**Comment by expln** [comment]
Ok. If something is still cannot be done with the software you have, just let me know, I will check if I can do it.

**Comment by david-a-wheeler** [comment]
The videos I plan to do for now are done. The videos in the [Metamath-lamp play list](https://www.youtube.com/playlist?list=PL1jSu6GGefBk3RhHW5Srpc2qxWMqhga9J) cover a lot of ground!

Note: "Introduction to metamath-lamp, part 2" in particular is getting a surprising number of views. I only switched it to "public" yesterday, and it's gotten 364 views since it was published. For a video on a proof assistant that's a surprising number of views in such a short time. Youtube's algorithms are starting to recommend it to other people without me doing anything, who are then actually watching it - which is interesting by itself. Watch out, I suspect there are more people starting think about using this tool :-).

I intend to eventually do videos for `syl` and `reccot`, but it's likely that adding full unification for global substitution will change that material. So I think I'll wait to create new videos until full unification is in place (at least for global substitution). I also have to do other things with my life for a bit :-). In any case, there's now *substantive* documentation for metamath-lamp, and some videos with sound that walk through it. If someone wants to use metamath-lamp, they now have a lot more material to learn from.

So I'm going to close this issue for now, as we *have* videos.

**Comment by expln** [comment]
In almost a month a lot of documentation and informative videos were created. This is a very good achievement! Now it's time for YouTube to do its work :)
