### ISSUE TITLE
Add images to explain bottom-up proving

### ISSUE THREAD

**Issue by david-a-wheeler** [metamath/lamp-guide#4]
Images are here https://drive.google.com/file/d/1kno1E4hYLZtZRsQ1KY88cLJxwv9Ir1f4/view?usp=sharing

**Comment by david-a-wheeler** [comment]
Some added notes from https://github.com/expln/metamath-lamp/pull/50 -

> You may find a brief explanation of the bottom-up prover settings here at 11:15 https://drive.google.com/file/d/1haJff_AN1M6HZGrWXsgqzrxq-Di84gmZ/view?t=675

> And particularly explanation of logging levels here at 13:31 https://drive.google.com/file/d/1haJff_AN1M6HZGrWXsgqzrxq-Di84gmZ/view?t=811

**Comment by expln** [comment]
There is also a demonstration of logging levels "in action" at 9:15 https://drive.google.com/file/d/1haJff_AN1M6HZGrWXsgqzrxq-Di84gmZ/view?t=555
