### ISSUE TITLE
Naming a hypothesis with a numeric value?

### ISSUE THREAD

**Issue by billh0420** [metamath/lamp-guide#47]
I am using the editor with no intention of saving the proof generated.

I have the following quirk when I try to enter a hypothesis and name it.

If I try to name it with a low number like 7 it gives an error message "Cannot reuse label '7' [1]."

So I thought I couldn't name it with a numeric value. But, if I name it with 42 or some large number, it accepts it.

This is confusing.

**Comment by david-a-wheeler** [comment]
The statement number has to be unique. If you already have something numbered '7' then it will fail. Otherwise it *should* just work.

If it is *not* working, then please file an issue against the tool:
https://github.com/expln/metamath-lamp
This repo only covers the documentation of the tool, the tool itself has its own repo.

**Comment by expln** [comment]
> If I try to name it with a low number like 7 it gives an error message "Cannot reuse label '7' [1]."

It is not allowed to use already declared math symbols as labels for hypotheses. 

In the Metamath book, on the page 114, there is a statement `Each label token must be unique, and no label token may match any math symbol token.`

In this case, `7` is an already defined math symbol -  it is a constant `$c 7 $. $( The decimal number 7 $)`. So you cannot label a hypothesis as `7`. As for `42`, this math symbol is not defined, so you can use it.

There is a related issue in the mm-lamp repo which should reduce such confusions - https://github.com/expln/metamath-lamp/issues/32

**Comment by david-a-wheeler** [comment]
I think the lamp-guide needs to be modified, in both the tutorial and reference sections, to make this clearer.

I agree with @expln that the automatic renaming of hypothesis will probably reduce the likelihood of this problem.

**Comment by david-a-wheeler** [comment]
Pull request #59 will clearly document this, in both the tutorial and reference manual. That should resolve it.
