### ISSUE TITLE
Implement https://lamp-guide.metamath.org

### ISSUE THREAD

**Issue by david-a-wheeler** [metamath/lamp-guide#6]
Pointing to the markdown file *works*, but the results are ugly.

Use GitHub pages so you can just open this and read the documentation:

https://lamp-guide.metamath.org

This requires moving `guide.md` to `index.md` (it can stay in `docs/`), configuration of GitHub pages, configuration of DNS. Once that works, I'm sure there will be fiddling needed to have a reasonable (style) template and probably some steps to complete the configuration.

**Comment by expln** [comment]
I [updated](https://github.com/expln/metamath-lamp/commit/03a19a7ffda8710c18630861aa68d87d132252b7) the reference. Everything works fine. Thank you.

> It'd be nice to have numbered headings via the CSS.

I will check in some time.

**Comment by david-a-wheeler** [comment]
The site <https://lamp-guide.metamath.org> works, and I've modified the CSS to have numbered headings. IDs can jump to headings (it requires JavaScript to be enabled, which is annoying but most people won't notice).

I think this is done.

I'll make "add a TOC" a new issue, that can be done later if ever.

**Comment by david-a-wheeler** [comment]
> It'd be nice to have numbered headings via the CSS.

FYI: I did this. I've modified the CSS to have numbered headings (as well as prevent awkward page breaks after a heading when printing).

**Comment by expln** [comment]
Excellent!
