### ISSUE TITLE
Rationalize "step" vs. "statement"

### ISSUE THREAD

**Issue by david-a-wheeler** [metamath/lamp-guide#62]

**Comment by david-a-wheeler** [comment]
I'm thinking about this nomenclature change in the guide.

I now think I should say that a "proof consists of many steps", and each step includes an id, step type (H/P/G), justification (hyp and ref), and statement. Currently I use the terms "statement" and "step" interchangeably, but I think that's become confusing.

Comments welcome.

**Comment by david-a-wheeler** [comment]
@expln - thoughts?

**Comment by expln** [comment]
I agree, "step" sounds more correct. You provide a statement, then say how we treat it - as a hypothesis (H) or it can be inferred from the previous (P/G) - all of these forms a step.

**Comment by david-a-wheeler** [comment]
Ok. The "Settings" panel has some fields that should eventually be changed to match. E.g. "Initial statement is goal" might be better said as "Initial step is goal".

I can probably add something like: "technically a step includes a statement, along with other information such as the label. Informally we will sometimes use the term statement for the whole step, because the statement is a key part of the step."

**Comment by david-a-wheeler** [comment]
Note: Sometimes "statement" should stay as "statement". E.g., "initial step is goal" (it's referring to the whole thing), but "edit statement by" is correct (because it's referring to the statement within a step).

Also, I'm *only* talking about the UI here. It might be good if the code eventually used the same terminology as the UI, but that's a lot of thankless work that's easily postponed :-).

**Comment by expln** [comment]
> "Settings" panel has some fields that should eventually be changed to match. E.g. "Initial statement is goal" might be better said as "Initial step is goal".

Ok, I will update the UI. (https://github.com/expln/metamath-lamp/issues/89)

> I can probably add something like: "technically a step includes a statement, along with other information such as the label. Informally we will sometimes use the term statement for the whole step, because the statement is a key part of the step."

Yeah, this sounds good.

> Also, I'm only talking about the UI here. It might be good if the code eventually used the same terminology as the UI, but that's a lot of thankless work that's easily postponed :-).

Yes, at some time, when I am done with main algorithms, I will work on code readability and will do such kind of refactorings.

**Comment by david-a-wheeler** [comment]
I've made the changes to rationalize "step" vs. "statement". I've added a double-dagger where the UI says "statement" but means "step"; once v11 comes out with an updated UI we can rapidly fix those.
